INSERT INTO `variables` (`variable_id`, `flag`, `variable_name`, `variable_info`, `field`, `sequence_id`, `type`, `dropdown_values`) VALUES
(129, 1, 'Full Name', 'dsgehy', '<input type="text" name="Full Name"/>', 12, 'Textbox', ''),
(202, 1, '{SEQ_3EAMP-VAR3}', 'Enter the name of the product here.', '<input type="text" name="{SEQ_3EAMP-VAR3}"/>', 3, 'Textbox', ''),
(203, 1, '{SEQ_3EAMP-VAR4}', 'Insert a special feature or benefit of the product here. (removes the confusion from building your own website, makes losing weight a total breeze)', '<textarea name="{SEQ_3EAMP-VAR4}"></textarea>', 3, 'Multiline', ''),
(201, 1, '{SEQ_3EAMP-VAR2}', 'Select a proof statement.', '<select name="3eamp-var2"><option value="proven to work">proven to work</option><option value=" well documented"> well documented</option><option value=" featured on major news outlets"> featured on major news outlets</option></select>', 3, 'Dropdown', ''),
(199, 1, '{SEQ_2EAMP-VAR15}', 'The third reason you like the course.', '<textarea name="{SEQ_2EAMP-VAR15}"></textarea>', 2, 'Multiline', ''),
(200, 1, '{SEQ_3EAMP-VAR1}', 'Enter the link to the product you want to promote here.', '<input type="text" name="{SEQ_3EAMP-VAR1}"/>', 3, 'Textbox', ''),
(198, 1, '{SEQ_2EAMP-VAR14}', 'Another reason you like the course.', '<textarea name="{SEQ_2EAMP-VAR14}"></textarea>', 2, 'Multiline', ''),
(197, 1, '{SEQ_2EAMP-VAR13}', 'One of the reasons you like the course.', '<textarea name="{SEQ_2EAMP-VAR13}"></textarea>', 2, 'Multiline', ''),
(196, 1, '{SEQ_2EAMP-VAR12}', 'The problem with similar products. (incomplete information, false claims)', '<input type="text" name="{SEQ_2EAMP-VAR12}"/>', 2, 'Textbox', ''),
(194, 1, '{SEQ_2EAMP-VAR11}', 'Enter the industry here (gardening, health and fitness, internet marketing)', '<input type="text" name="{SEQ_2EAMP-VAR11}"/>', 2, 'Textbox', ''),
(195, 1, '{SEQ_2EAMP-VAR12}', 'The problem with similar products. (Inaccurate information, false claims, incomplete instructions)', '<input type="text" name="{SEQ_2EAMP-VAR12}"/>', 2, 'Textbox', ''),
(193, 1, '{SEQ_2EAMP-VAR10}', 'What the product solves or does (getting unlimited traffic, building the perfect treehouse)', '<input type="text" name="{SEQ_2EAMP-VAR10}"/>', 2, 'Textbox', ''),
(192, 1, '{SEQ_2EAMP-VAR9}', 'Put the product owners name here.', '<input type="text" name="{SEQ_2EAMP-VAR9}"/>', 2, 'Textbox', ''),
(191, 1, '{SEQ_2EAMP-VAR8}', 'Put the name of an endangered species here (Dodo bird, spotted whale)', '<input type="text" name="{SEQ_2EAMP-VAR8}"/>', 2, 'Textbox', ''),
(190, 1, '{SEQ_2EAMP-VAR7}', 'Guarantee length (60 days, 6 weeks)', '<input type="text" name="{SEQ_2EAMP-VAR7}"/>', 2, 'Textbox', ''),
(189, 1, '{SEQ_2EAMP-VAR6}', 'The Affiliate product owners name. (Paul, Thomas)', '<input type="text" name="{SEQ_2EAMP-VAR6}"/>', 2, 'Textbox', ''),
(188, 1, '{SEQ_2EAMP-VAR5}', 'Enter some results here (amount of weight people are losing, amount of money people are making, how beautiful my garden is)', '<input type="text" name="{SEQ_2EAMP-VAR5}"/>', 2, 'Textbox', ''),
(187, 1, '{SEQ_2EAMP-VAR4}', 'Enter the type of product here. (videos, modules, ebooks)', '<input type="text" name="{SEQ_2EAMP-VAR4}"/>', 2, 'Textbox', ''),
(186, 1, '{SEQ_2EAMP-VAR3}', 'Enter your affiliate link or redirect link here.', '<input type="text" name="{SEQ_2EAMP-VAR3}"/>', 2, 'Textbox', ''),
(184, 1, '{SEQ_2EAMP-VAR1}', 'Enter the name of an endangered species here (dodo bird)', '<input type="text" name="{SEQ_2EAMP-VAR1}"/>', 2, 'Textbox', ''),
(185, 1, '{SEQ_2EAMP-VAR2}', 'The problem the product solves. (make money online, lose weight)', '<input type="text" name="{SEQ_2EAMP-VAR2}"/>', 2, 'Textbox', ''),
(204, 1, '{SEQ_3EAMP-VAR5}', 'Put the product owners name here.', '<input type="text" name="{SEQ_3EAMP-VAR5}"/>', 3, 'Textbox', ''),
(205, 1, '{SEQ_3EAMP-VAR6}', 'Enter bonus information or a breakdown of the guarantee here. (5 awesome bonuses, a full 60 day money-back guarantee)', '<textarea name="{SEQ_3EAMP-VAR6}"></textarea>', 3, 'Multiline', ''),
(206, 1, '{SEQ_2EAMP-VAR22}', 'The problem with similar products. (incomplete information, false claims)', '<input type="text" name="{SEQ_2EAMP-VAR22}"/>', 2, 'Textbox', ''),
(207, 1, '{SEQ_3EAMP-VAR22}', 'Goal the user wants to achieve. (lose weight, make money)', '<input type="text" name="{SEQ_3EAMP-VAR22}"/>', 3, 'Textbox', ''),
(208, 1, '{SEQ_3DES-VAR1}', 'Enter the topic of your event here. (Kindle Publishing, Easy Weight Loss)', '<input type="text" name="{SEQ_3DES-VAR1}"/>', 4, 'Textbox', ''),
(209, 1, '{SEQ_3DES-VAR2}', 'Enter your event type here (Webinar, Teleseminar, Podcast, Live Training)', '<input type="text" name="{SEQ_3DES-VAR2}"/>', 4, 'Textbox', ''),
(210, 1, '{SEQ_3DES-VAR3}', 'Enter a shocking fact here. (9 out of 10 people who try to lose weight fail!)', '<textarea name="{SEQ_3DES-VAR3}"></textarea>', 4, 'Multiline', ''),
(211, 1, '{SEQ_3DES-VAR4}', 'Enter a reason why this fact is true. (People find it difficult to feel hungry)', '<textarea name="{SEQ_3DES-VAR4}"></textarea>', 4, 'Multiline', ''),
(212, 1, '{SEQ_3DES-VAR5}', 'Enter a second supporting reason your fact is true.', '<textarea name="{SEQ_3DES-VAR5}"></textarea>', 4, 'Multiline', ''),
(213, 1, '{SEQ_3DES-VAR6}', 'Enter a third and final reason your fact is true.', '<textarea name="{SEQ_3DES-VAR6}"></textarea>', 4, 'Multiline', ''),
(214, 1, '{SEQ_3DES-VAR7}', 'Reason you identify with the audience. (I remember how hard it was for me to start making money online)', '<textarea name="{SEQ_3DES-VAR7}"></textarea>', 4, 'Multiline', ''),
(215, 1, '{SEQ_3DES-VAR8}', 'What your audience will learn at the event (uncover the secret to instant and permanent weight loss)', '<textarea name="{SEQ_3DES-VAR8}"></textarea>', 4, 'Multiline', ''),
(216, 1, '{SEQ_3DES-VAR9}', 'Enter your event details here. (The time, date, call in numbers, or website links)', '<textarea name="{SEQ_3DES-VAR9}"></textarea>', 4, 'Multiline', ''),
(217, 1, '{SEQ_3DES-VAR10}', 'What you will be teaching at the event. (getting your products published on the Kindle, getting more traffic to your website)', '<textarea name="{SEQ_3DES-VAR10}"></textarea>', 4, 'Multiline', ''),
(218, 1, '{SEQ_3DES-VAR11}', 'Who has the proof? (I, Larry Winget, a single mother of four)', '<input type="text" name="{SEQ_3DES-VAR11}"/>', 4, 'Textbox', ''),
(219, 1, '{SEQ_3DES-VAR12}', 'What did that person accomplish? (lose 40 pounds in three months, turn himself into a household name)', '<textarea name="{SEQ_3DES-VAR12}"></textarea>', 4, 'Multiline', ''),
(220, 1, '{SEQ_3DES-VAR13}', 'Reframe the topic. (Mobile publishing secrets)', '<input type="text" name="{SEQ_3DES-VAR13}"/>', 4, 'Textbox', ''),
(221, 1, '{SEQ_3DES-VAR14}', 'Enter a bullet here. Something people will learn or a benefit of attending. (Discover five foods that supercharge your metabolism)', '<textarea name="{SEQ_3DES-VAR14}"></textarea>', 4, 'Multiline', ''),
(222, 1, '{SEQ_3DES-VAR15}', 'Another bullet here.', '<textarea name="{SEQ_3DES-VAR15}"></textarea>', 4, 'Multiline', ''),
(223, 1, '{SEQ_3DES-VAR16}', 'Enter a third and final bullet here.', '<textarea name="{SEQ_3DES-VAR16}"></textarea>', 4, 'Multiline', ''),
(224, 1, '{SEQ_3DES-VAR17}', 'Tell the audience what to do next. (Listen to the replay, grab a copy of the product)', '<input type="text" name="{SEQ_3DES-VAR17}"/>', 4, 'Textbox', ''),
(225, 1, '{SEQ_3DES-VAR18}', 'The link to buy your product or listen to the replay.', '<input type="text" name="{SEQ_3DES-VAR18}"/>', 4, 'Textbox', ''),
(226, 1, '{SEQ_10EAPS-VAR1}', 'Enter the name of your newsletter here. (Traffic Insiders, Weight Loss Secrets)', '<input type="text" name="{SEQ_10EAPS-VAR1}"/>', 1, 'Textbox', ''),
(227, 1, '{SEQ_10EAPS-VAR2}', 'The goal of the newsletter. (lose weight, get more customers)', '<textarea name="{SEQ_10EAPS-VAR2}"></textarea>', 1, 'Multiline', ''),
(228, 1, '{SEQ_10EAPS-VAR3}', 'Enter the reason you identify with the reader. (I struggled with my weight, I remember what it was like to not have traffic)', '<textarea name="{SEQ_10EAPS-VAR3}"></textarea>', 1, 'Multiline', ''),
(229, 1, '{SEQ_10EAPS-VAR4}', 'Enter the link to the free content you gave them when they joined your list.', '<input type="text" name="{SEQ_10EAPS-VAR4}"/>', 1, 'Textbox', ''),
(230, 1, '{SEQ_10EAPS-VAR5}', 'What type of content did you give people when they subscribed?', '<select name="{SEQ_10EAPS-VAR5}"><option value="video">video</option><option value=" eBook"> eBook</option><option value=" report"> report</option><option value=" article"> article</option></select>', 1, 'Dropdown', ''),
(231, 1, '{SEQ_10EAPS-VAR6}', 'Enter the title of what you gave them. (Rapid Weight Loss, Extreme Traffic, Affiliate Powerhouse)', '<input type="text" name="{SEQ_10EAPS-VAR6}"/>', 1, 'Textbox', ''),
(232, 1, '{SEQ_10EAPS-VAR7}', 'One important thing you cover in the free content you gave them. (how to get your website up and running in mere minutes, the importance of a balanced diet)', '<textarea name="{SEQ_10EAPS-VAR7}"></textarea>', 1, 'Multiline', ''),
(233, 1, '{SEQ_10EAPS-VAR8}', 'What is the benefit of that important thing? (get up and running as quickly as possible, boost your metabolism and kick-start rapid weight loss)', '<textarea name="{SEQ_10EAPS-VAR8}"></textarea>', 1, 'Multiline', ''),
(234, 1, '{SEQ_10EAPS-VAR9}', 'How long will it take for people to go through your free content?', '<select name="{SEQ_10EAPS-VAR9}"><option value="a couple minutes">a couple minutes</option><option value=" 5 minutes or so"> 5 minutes or so</option><option value=" 10 minutes or so"> 10 minutes or so</option><option value=" 30 minutes"> 30 minutes</option></select>', 1, 'Dropdown', ''),
(235, 1, '{SEQ_10EAPS-VAR10}', 'What should they do if they have questions?', '<select name="{SEQ_10EAPS-VAR10}"><option value="email me">email me</option><option value=" connect on Facebook"> connect on Facebook</option><option value=" submit a support ticket"> submit a support ticket</option><option value=" call our hotline"> call our hotline</option></select>', 1, 'Dropdown', ''),
(236, 1, '{SEQ_10EAPS-VAR11}', 'What is the link for support?', '<input type="text" name="{SEQ_10EAPS-VAR11}"/>', 1, 'Textbox', ''),
(237, 1, '{SEQ_10EAPS-VAR12}', 'Tell a personal story here. (Talk about why this information is so important to you, The impact it has had on you, etc. etc.)', '<textarea name="{SEQ_10EAPS-VAR12}"></textarea>', 1, 'Multiline', ''),
(238, 1, '{SEQ_10EAPS-VAR13}', 'Something that made an immediate impact for you.', '<select name="10EAPS-VAR13"><option value="the right information">the right information</option><option value=" a solid game plan"> a solid game plan</option><option value=" a community I could count on"> a community I could count on</option><option value=" someone I could trust"> someone I could trust</option></select>', 1, 'Dropdown', ''),
(239, 1, '{SEQ_10EAPS-VAR14}', 'A topic that is covered in the next affiliate product you are about to promote. It is best if this is something you have not covered yet. Or something controversial.', '<input type="text" name="{SEQ_10EAPS-VAR14}"/>', 1, 'Textbox', ''),
(240, 1, '{SEQ_10EAPS-VAR15}', 'Topic of the article, blog post, news story, or video.', '<input type="text" name="{SEQ_10EAPS-VAR15}"/>', 1, 'Textbox', ''),
(241, 1, '{SEQ_10EAPS-VAR16}', 'Type of content.', '<select name="10EAPS-VAR16"><option value="article">article</option><option value=" video"> video</option><option value=" blog post"> blog post</option><option value=" news story"> news story</option></select>', 1, 'Dropdown', ''),
(242, 1, '{SEQ_10EAPS-VAR17}', 'Link to article, blog post, video, or news story.', '<input type="text" name="{SEQ_10EAPS-VAR17}"/>', 1, 'Textbox', ''),
(243, 1, '{SEQ_10EAPS-VAR18}', 'Enter a personal story here. Tie it to a recommendation.', '<textarea name="{SEQ_10EAPS-VAR18}"></textarea>', 1, 'Multiline', ''),
(244, 1, '{SEQ_10EAPS-VAR19}', 'What does the reader wants to solve or achieve? (losing weight, making money online, getting more customers, having a healthy organic garden)', '<input type="text" name="{SEQ_10EAPS-VAR19}"/>', 1, 'Textbox', ''),
(245, 1, '{SEQ_10EAPS-VAR20}', 'What are you selling them? (battle plan, balance of nutrients, road map, step-by-step system)', '<input type="text" name="{SEQ_10EAPS-VAR20}"/>', 1, 'Textbox', ''),
(246, 1, '{SEQ_10EAPS-VAR21}', 'Enter your affiliate link or redirect here.', '<input type="text" name="{SEQ_10EAPS-VAR21}"/>', 1, 'Textbox', ''),
(247, 1, '{SEQ_10EAPS-VAR22}', 'Problem the reader is struggling with. (still struggling to lose weight? still beating your head against the affiliate marketing wall?)', '<textarea name="{SEQ_10EAPS-VAR22}"></textarea>', 1, 'Multiline', ''),
(248, 1, '{SEQ_10EAPS-VAR23}', 'Your affiliate link goes here.', '<input type="text" name="{SEQ_10EAPS-VAR23}"/>', 1, 'Textbox', ''),
(249, 1, '{SEQ_10EAPS-VAR24}', 'Why your recommended product is so great. (What you like about it, why it is better than others, what it solves, what your results were like)', '<textarea name="{SEQ_10EAPS-VAR24}"></textarea>', 1, 'Multiline', ''),
(250, 1, '{SEQ_10EAPS-VAR25}', 'What they should do.', '<select name="10EAPS-VAR25"><option value="Read more">Read more</option><option value=" Watch the video"> Watch the video</option><option value=" Check it out"> Check it out</option><option value=" Get the free report"> Get the free report</option><option value=" Get the free video"> Get the free video</option></select>', 1, 'Dropdown', ''),
(251, 1, '{SEQ_10EAPS-VAR26}', 'The topic the product covers.', '<input type="text" name="{SEQ_10EAPS-VAR26}"/>', 1, 'Textbox', ''),
(252, 1, '{SEQ_10EAPS-VAR27}', 'What is the product? (training, eBook, videos)', '<input type="text" name="{SEQ_10EAPS-VAR27}"/>', 1, 'Textbox', ''),
(253, 1, '{SEQ_10EAPS-VAR28}', 'Question you get asked the most.', '<input type="text" name="{SEQ_10EAPS-VAR28}"/>', 1, 'Textbox', ''),
(254, 1, '{SEQ_10EAPS-VAR29}', 'Answer to the question (in your opinion)', '<textarea name="{SEQ_10EAPS-VAR29}"></textarea>', 1, 'Multiline', ''),
(255, 1, '{SEQ_10EAPS-VAR30}', 'Link to article, video, blog post, or news story.', '<input type="text" name="{SEQ_10EAPS-VAR30}"/>', 1, 'Textbox', ''),
(256, 1, '{SEQ_10EAPS-VAR31}', 'Type of content you are linking to.', '<select name="10EAPS-VAR31"><option value="blog post">blog post</option><option value=" article"> article</option><option value=" video"> video</option><option value=" news story"> news story</option><option value=" interview"> interview</option></select>', 1, 'Dropdown', ''),
(257, 1, '{SEQ_10EAPS-VAR32}', 'Topic you have not talked about yet, but something really important.', '<input type="text" name="{SEQ_10EAPS-VAR32}"/>', 1, 'Textbox', ''),
(258, 1, '{SEQ_10EAPS-VAR33}', 'Expand on that topic. What does it create or provide? (a dedicated exercise plan, a traffic strategy, a firm understanding of soil nutrients)', '<input type="text" name="{SEQ_10EAPS-VAR33}"/>', 1, 'Textbox', ''),
(259, 1, '{SEQ_10EAPS-VAR34}', 'What the reader wants. (have a healthy garden, lose those extra pounds, get the traction your business needs)', '<textarea name="{SEQ_10EAPS-VAR34}"></textarea>', 1, 'Multiline', ''),
(260, 1, '{SEQ_10EAPS-VAR35}', 'What should the reader do?', '<select name="10EAPS-VAR35"><option value="Watch">Watch</option><option value=" read"> read</option><option value=" check out"> check out</option><option value=" download"> download</option><option value=" listen to"> listen to</option></select>', 1, 'Dropdown', ''),
(261, 1, '{SEQ_10EAPS-VAR36}', 'And what exactly is it? (video, article, podcast, free report)', '<input type="text" name="{SEQ_10EAPS-VAR36}"/>', 1, 'Textbox', ''),
(262, 1, '{SEQ_10EAPS-VAR37}', 'Link to the page you are promoting or the content you want to share.', '<input type="text" name="{SEQ_10EAPS-VAR37}"/>', 1, 'Textbox', '');
